import type { AppState } from "./types";

export const state: AppState = {
  page: 1,
  pageSize: 20,
  filters: { q: "", type: "", status: "", draw: "", drawWindow: "", sort: "", order: "" },
  polling: null,
  logDockOpen: false,
  autoDockOpen: false,
  autoScheduler: null,
  autoPollTimer: null,
  autoCountdownTimer: null,
  autoServerSkewMs: 0,
  autoLogs: [],
  qrcodeDismissed: false,
  lastQrcodeRefresh: 0,
  account: null,
  settings: null,
  atAlertShownKey: "",
  tripleTargets: { count: 0, limit: 3, items: [] },
  tripleFilterKey: "",
  smoothJobPercent: 0,
  activeJobKey: "",
  jobResultTimer: null,
  watchUsers: null,
  lastJobAttempt: null,
  onboardingCelebrating: false,
  statValues: {},
  currentJob: null,
  eventSource: null,
  sseHealthy: false,
  sseLastActive: 0,
  sseWatchdog: null,
  sseReconnectTimer: null,
  lastFinishedJobKey: "",
};
